logging:
  config: classpath:logback-spring.xml
server:
  port: 37270
spring:
  application:
    name: quantization-knowledge
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.43.110.173:30370/knowledge?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo@2022
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  redis:
    host: 101.43.110.173
    port: 33370
    password: 
    timeout: 6000
    lettuce:
      pool:
        max-wait: 60000
        max-active: 10
        max-idle: 5
        min-idle: 0
logstash: 
  destination: 101.43.110.173:37370
mybatis:
  type-aliases-package: com.personal.quantization.knowledge.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true