server:
  port: 38370
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: quantization-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: quantization-front
          uri: lb://quantization-front
          predicates:
            - Path=/quantization/**
        - id: quantization-center
          uri: lb://quantization-center
          predicates:
            - Path=/center/**
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
    sentinel:
      transport:
        dashboard: 101.43.110.173:30270
        clientIp: 101.43.110.173
  sentinel:
    eager: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.43.110.173:30370/quantization_2022?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo@2022
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  redis:
    host: 101.43.110.173
    port: 33370
    password: 
    timeout: 6000
    lettuce:
      pool:
        max-wait: 60000
        max-active: 10
        max-idle: 5
        min-idle: 0

logstash: 
  destination: 101.43.110.173:37370
mybatis:
  type-aliases-package: com.personal.quantization.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
custom:
  rest:
    template:
      connect-timeout: 5000
      read-timeout: 5000
feign:
  compression:
    request:
      enabled: true
      mime-types:
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true