server:
  port: 39270
  servlet:
    context-path: /auth
  logging:
  level:
    org:
      springframework:
        web: info
    root: debug
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    charset: UTF-8
    content-type: text/html
    enabled: true
    request-context-attribute: rc
    suffix: .html

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.43.110.173:30370/user_db?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo@2022
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 101.43.110.173
    port: 33370
    password: 
    timeout: 6000
    lettuce:
      pool:
        max-wait: 60000
        max-active: 10
        max-idle: 5
        min-idle: 0
feign:
  compression:
    request:
      enabled: true
      mime-types:
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env